/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrderStatus } from '../models/order-status';
export interface Order {
  amount?: number;
  id?: number;
  orderStatusId?: string;
  productId?: string;
  status?: OrderStatus;
}
