name: order-ms push

env:
  EWS_REGION: eu-north-1
  EWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  EWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}
  ECS_SERVICE: ${{ secrets.ECS_SERVICE }}
  ECS_TASK_DEFINITION: spring-boo-app-task-definition

on:
  workflow_dispatch:
jobs:
  build:
    name: Build Image
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
    defaults:
      run:
          working-directory: ./order-ms
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: clear project
      run: mvn clean
    - name: compile the project
      run: mvn compile
    - name: run test case
      run: mvn test
    - name: Build with Maven
      run: mvn clean install package
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: demo-inventory/order-ms
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Update Task Definition
      uses: yumemi-inc/update-ecs-task-definition-action@v1
      with:
        family: spring-boo-app-task-definition
        images: |
          spring-boot-order-ms=084375582288.dkr.ecr.eu-north-1.amazonaws.com/demo-inventory/order-ms:latest
